### ISSUE TITLE
Port repositories to GA4GH org

### ISSUE THREAD

**Issue by monicacecilia** [ga4gh/pedigree_family_history_terminology#46]
Port all repositories in this Org to the GA4GH Org.

Dear @lindsmith, could I kindly ask if we could please initiate the move of this and the other four repositories to live within the GA4GH GH Org? What should we do? Who do we talk to over there? 

In the meantime, could we please add @balhoff and @cmungall as team members with Owner privileges to the [family_history_terminology](https://github.com/GA4GH-Pedigree-Standard/family_history_terminology) repository? 

(who is Jimmy Paul? 🌷)

@buske 👀 👆🏽

**Comment by lindsmith** [comment]
I have connected with @jppay (Jimmy Paul, GA4GH tech team staff at EBI) and he will help with migration. I've made him an owner of the Pedigree Github org.

@balhoff and @cmungall - just sent you both invites with admin privileges. Please let me know if they didn't come through!

**Comment by monicacecilia** [comment]
Thank you, @jppay and @lindsmith!
