### ISSUE TITLE
Review and Edit KIN->FHIR FamilyMemberHistory codes in SSSOM

### ISSUE THREAD

**Issue by tripb** [ga4gh/pedigree_family_history_terminology#48]
Here: https://github.com/ga4gh/pedigree_family_history_terminology/blob/main/mappings/kin-to-fhir-FamilyMember.sssom.csv

vs: https://terminology.hl7.org/5.1.0/ValueSet-v3-FamilyMember.html

**Comment by tripb** [comment]
@cmungall - Is this mapping to 'v5.1.0: Release' or different version of FHIR?  Thank you.

**Comment by cmungall** [comment]
I downloaded http://terminology.hl7.org/CodeSystem/v3-RoleCode on June 14, #44

It looks like this currently resolves to
https://terminology.hl7.org/6.0.2/CodeSystem-v3-RoleCode.html

Which is dated 2019, so I assume it was this version

Just to emphasize this was intended as a first pass!

**Comment by tripb** [comment]
Closed by https://github.com/ga4gh/pedigree_family_history_terminology/pull/49
